package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Jan, 2016 3:14:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ConformationMailQueue generated by hbm2java
 */
public class ConformationMailQueue  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Byte status;
     private Date intime;
     private Date outtime;
     private Date endtime;
     private Date lastupdate;

    public ConformationMailQueue() {
    }

	
    public ConformationMailQueue(Date lastupdate) {
        this.lastupdate = lastupdate;
    }
    public ConformationMailQueue(Integer employeeId, Byte status, Date intime, Date outtime, Date endtime, Date lastupdate) {
       this.employeeId = employeeId;
       this.status = status;
       this.intime = intime;
       this.outtime = outtime;
       this.endtime = endtime;
       this.lastupdate = lastupdate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Date getIntime() {
        return this.intime;
    }
    
    public void setIntime(Date intime) {
        this.intime = intime;
    }
    public Date getOuttime() {
        return this.outtime;
    }
    
    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }




}


