package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Jan, 2016 3:14:25 PM by Hibernate Tools 4.3.1



/**
 * EmployeeXRoleGroup generated by hbm2java
 */
public class EmployeeXRoleGroup  implements java.io.Serializable {


     private EmployeeXRoleGroupId id;

    public EmployeeXRoleGroup() {
    }

    public EmployeeXRoleGroup(EmployeeXRoleGroupId id) {
       this.id = id;
    }
   
    public EmployeeXRoleGroupId getId() {
        return this.id;
    }
    
    public void setId(EmployeeXRoleGroupId id) {
        this.id = id;
    }




}


