package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Jan, 2016 3:14:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String surName;
     private int telephone;
     private byte gender;
     private String emailId;
     private Date employeeJoiningDate;
     private Date dateOfBirth;
     private byte verified;
     private byte deleted;
     private Date lastUpdated;
     private EmployeeXLogin employeeXLogin;
     private VerificationToken verificationToken;

    public Employee() {
    }

	
    public Employee(String firstName, String surName, int telephone, Byte gender, String emailId, byte verified, byte deleted, Date lastUpdated) {
        this.firstName = firstName;
        this.surName = surName;
        this.telephone = telephone;
        this.gender = gender;
        this.emailId = emailId;
        this.verified = verified;
        this.deleted = deleted;
        this.lastUpdated = lastUpdated;
    }
    public Employee(String firstName, String surName, int telephone, Byte gender, String emailId, Date employeeJoiningDate, Date dateOfBirth, byte verified, byte deleted, Date lastUpdated, EmployeeXLogin employeeXLogin, VerificationToken verificationToken) {
       this.firstName = firstName;
       this.surName = surName;
       this.telephone = telephone;
       this.gender = gender;
       this.emailId = emailId;
       this.employeeJoiningDate = employeeJoiningDate;
       this.dateOfBirth = dateOfBirth;
       this.verified = verified;
       this.deleted = deleted;
       this.lastUpdated = lastUpdated;
       this.employeeXLogin = employeeXLogin;
       this.verificationToken = verificationToken;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSurName() {
        return this.surName;
    }
    
    public void setSurName(String surName) {
        this.surName = surName;
    }
    public int getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }
   
    
    
    public byte getGender() {
		return gender;
	}


	public void setGender(byte gender) {
		this.gender = gender;
	}


	public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public Date getEmployeeJoiningDate() {
        return this.employeeJoiningDate;
    }
    
    public void setEmployeeJoiningDate(Date employeeJoiningDate) {
        this.employeeJoiningDate = employeeJoiningDate;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public byte getVerified() {
        return this.verified;
    }
    
    public void setVerified(byte verified) {
        this.verified = verified;
    }
    public byte getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(byte deleted) {
        this.deleted = deleted;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public EmployeeXLogin getEmployeeXLogin() {
        return this.employeeXLogin;
    }
    
    public void setEmployeeXLogin(EmployeeXLogin employeeXLogin) {
        this.employeeXLogin = employeeXLogin;
    }
    public VerificationToken getVerificationToken() {
        return this.verificationToken;
    }
    
    public void setVerificationToken(VerificationToken verificationToken) {
        this.verificationToken = verificationToken;
    }


	@Override
	public String toString() {
		return "Employee [id=" + id + ", firstName=" + firstName + ", surName="
				+ surName + ", telephone=" + telephone + ", gender=" + gender
				+ ", emailId=" + emailId + ", employeeJoiningDate="
				+ employeeJoiningDate + ", dateOfBirth=" + dateOfBirth
				+ ", verified=" + verified + ", deleted=" + deleted
				+ ", lastUpdated=" + lastUpdated + ", employeeXLogin="
				+ employeeXLogin + ", verificationToken=" + verificationToken
				+ "]";
	}




}


