package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Jan, 2016 3:14:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmployeeXLogin generated by hbm2java
 */
public class EmployeeXLogin  implements java.io.Serializable {


     private int employeeId;
     private Employee employee;
     private String username;
     private String password;
     private Date lastUpdate;

    public EmployeeXLogin() {
    }

	
    public EmployeeXLogin(Employee employee, Date lastUpdate) {
        this.employee = employee;
        this.lastUpdate = lastUpdate;
    }
    public EmployeeXLogin(Employee employee, String username, String password, Date lastUpdate) {
       this.employee = employee;
       this.username = username;
       this.password = password;
       this.lastUpdate = lastUpdate;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


