package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Jan, 2016 3:14:25 PM by Hibernate Tools 4.3.1



/**
 * RoleXGroup generated by hbm2java
 */
public class RoleXGroup  implements java.io.Serializable {


     private RoleXGroupId id;

    public RoleXGroup() {
    }

    public RoleXGroup(RoleXGroupId id) {
       this.id = id;
    }
   
    public RoleXGroupId getId() {
        return this.id;
    }
    
    public void setId(RoleXGroupId id) {
        this.id = id;
    }




}


