package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Jan, 2016 3:14:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VerificationToken generated by hbm2java
 */
public class VerificationToken  implements java.io.Serializable {


     private int empId;
     private Employee employee;
     private String token;
     private Date expireDate;
     private Date lastUpdated;

    public VerificationToken() {
    }

	
    public VerificationToken(Employee employee, Date lastUpdated) {
        this.employee = employee;
        this.lastUpdated = lastUpdated;
    }
    public VerificationToken(Employee employee, String token, Date expireDate, Date lastUpdated) {
       this.employee = employee;
       this.token = token;
       this.expireDate = expireDate;
       this.lastUpdated = lastUpdated;
    }
   
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


