package de.employeeapp.dao.model.employeeManagementSystem;
// Generated 14 Dec, 2015 9:31:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VerificationToken generated by hbm2java
 */
public class VerificationToken  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private String token;
     private Date expireDate;
     private Date lastUpdated;

    public VerificationToken() {
    }

	
    public VerificationToken(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public VerificationToken(Employee employee, String token, Date expireDate, Date lastUpdated) {
       this.employee = employee;
       this.token = token;
       this.expireDate = expireDate;
       this.lastUpdated = lastUpdated;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


